# Generated by Django 2.2.4 on 2019-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_itemorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
